[platformio]
src_dir = Src
default_envs = VARIANT_USART

[env:VARIANT_USART]
platform = ststm32
framework = stm32cube
board = genericSTM32F103RC
debug_tool = stlink
upload_protocol = stlink
monitor_speed = 115200

build_src_flags =
    -Wall
    -Wextra
    -Werror

build_flags =
    -I.
    -ISrc
    -DUSE_HAL_DRIVER
    -DSTM32F103xE
    -DVARIANT_USART
    -T./STM32F103RCTx_FLASH.ld
    -lc
    -lm
    -g
    -ggdb
